// /** @type {import('next').NextConfig} */
// const nextConfig = {
//   reactStrictMode: true,
// }
// const withBundleAnalyzer = require('@next/bundle-analyzer')({
//   enabled: process.env.ANALYZE === 'true',
// });
const configJson = {
  assetPrefix: '',
  reactStrictMode: false,
  eslint: {
    ignoreDuringBuilds: true,
  },
  env: {
    REACT_APP_GOOGLE_CLIENT_ID: '875253336146-chist6efadea4bi8ts0s7qhelqp536b4.apps.googleusercontent.com',
    // WEBSITE_URL: 'http://localhost:3000/',
    WEBSITE_URL: 'https://dev.dsigndpo.com/',
    // WEBSITE_URL: 'https://www.dsigndpo.com/',
    BASE_API_URL: 'https://devapi.dsigndpo.com/web-api/',
    HOME_PAGE_DATA: 'home/configurations',
    CATEGORIES_DATA: 'home/categories',
    CATEGORIES_DESCRIPTION: 'category',
    HOME_DESIGNS_DATA: 'home/designs',
    EXPLORE_DESIGNS_DATA: 'designs',
    DESIGN_DETAIL_DATA: 'designs/detail',
    DESIGNS_FILTERS_DATA: 'designs/filters',
    DESIGNS_FILTERS_SIZE_DATA: 'designs/size-filters',
    SOCIAL_LOGIN: 'social-login',
    SEND_OTP: 'send-otp',
    REGISTER_LOGIN: 'register-login',
    SET_USER_ROLE: 'set-role',
    STATES_DATA: 'get-states',
    CITIES_DATA: 'get-cities',
    UPDATE_DEALER_PROFILE: 'update-dealer-info',
    ADD_TO_CART: 'users/add-to-cart',
    REMOVE_FROM_CART: 'users/remove-from-cart',
    CART_DATA: 'users/cart-data',
    WISHLIST_FOLDERS: 'users/wishlist-folders',
    WISHLIST_DESIGNS: 'users/wishlist-designs',
    WISHLIST_UNWISHLIST_DESIGN: 'users/wishlist-unwishlist-design',
    REMOVE_WISHLIST_FOLDER: 'users/remove-wishlist-folder',
    ADD_UPDATE_WISHLIST_FOLDER: 'users/add-update-wishlist-folder',
    USER_DETAILS_DATA: 'users/profile',
    USER_USER_PROFILE: 'users/update-profile',
    BUY_DESIGNS: 'users/buy-designs',
    PAYMENT_GATEWAY_RESPONSE: 'users/payment-gateway-response',
    ORDERS_LIST: 'users/orders',
    ORDER_DETAILS: 'users/order-detail',
    PLANS_LIST: 'plans',
    BUY_PLAN: 'users/buy-plan',
    PLANS_PAYMENT_STATUS: 'users/plan/check-paytm-order-status',
    PLANS_PAYMENT_RESPONSE: 'users/plan/payment-gateway-response',
    FAQ_DATA: 'faq',
    CMS_DATA: 'cms-page',
    DOWNLOAD_DESIGN: 'designs/download',
    CONTACT_US_FORM: 'cms-page/send-contact-us-email',
    COMPANY_DETAIL_DATA: 'cms-page/company-detail',
    SEARCH_DESIGNS_DATA: 'designs/search-designs',
    CMS_META_DATA: 'cms-page/cms-meta-tags',
    CMS_SEO_META_DATA: 'cms-page/seo-meta-tags',
    DESIGNS_META_DATA: 'designs/design-meta-tags',
    PAYMENT_STATUS_META_DATA: 'cms-page/payment-status-meta-tags',
    CHAT_CONNECTIONS: 'chat/get-chat-connections',
    USERS_CHAT_DATA: 'chat',
    CHAT_SEND_MESSAGE: 'chat/send-message',
    CHAT_READ: 'chat/mark-chat-read',
    SUBSCRIPTIONS_DATA: 'users/my-subscriptions',
    WITHDRAWAL_REQUEST: 'withdrawal-request/create-withdrawal-request',
    WITHDRAWAL_STATUS_DATA: 'withdrawal-request',
    TEMPLATES_DATA: 'templates',
    GENERATE_TEMPLATES_DATA: 'chat/generate-template-content',
    PENDING_CHAT: 'chat/get-unapproved-chats',
    SITEMAP_DATA: 'sitemap',
    CLEAR_CHAT: 'chat/delete-chats',
    FORWARD_MSG: 'chat/forward-message',
    DELETE_CONNECTION: 'chat/delete-chat-connection',
    CREATE_CHAT_CONNECTION: 'home/create-chat-connection',
  },
};

module.exports = configJson;
// module.exports = withBundleAnalyzer(configJson);